@jwt = 

#Signup for User - User Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "FilmCritic32",
  "email": "filmcritic@aol.com",
  "password": "password",
  "password_confirmation": "password"
}

#User Login
###
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "filmcritic@aol.com",
  "password": "password"
}


# For future requests - need to be logged in
# Authorization: Bearer {{ jwt }}