@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzg1ODYzODV9.j2rZvswkXME1zaFDmSusNdItpskyFXAjmxzeL1LAWH8

#Signup for User - User Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "FilmCritic32",
  "email": "filmcritic@aol.com",
  "password": "password",
  "password_confirmation": "password"
}

#User Login
###
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "filmcritic@aol.com",
  "password": "password"
}


# For future requests - need to be logged in
# Authorization: Bearer {{ jwt }}

#Show all of the media
###
GET http://localhost:3000/media


#Create Review
###
POST http://localhost:3000/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzg1ODYzODV9.j2rZvswkXME1zaFDmSusNdItpskyFXAjmxzeL1LAWH8
Content-Type: application/json

{
  "title": "This was MEH",
  "flix_rating": 5,
  "post": "This was a pretty disappoitning show - no development and slow to start. Not really recommend unless you are SUPER bored.",
  "medium_id": 150
}

###
DELETE http://localhost:3000/reviews/2
Authorization: Bearer


#Create comment
###
POST http://localhost:3000/comments
Authorization: Bearer
Content-Type: application/json

{
  "body": "That's an interesting opinion - have you seen the originals?"
}

###
DELETE http://localhost:3000/comments/1
Authorization: Bearer